services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: shop_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: shop-delivery-api
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shop_delivery
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data:
